export const keys: {label: string; type: string}[] = [
  {label: 'format', type: 'string'},
  {label: 'is_public', type: 'number'},
  {label: 'name', type: 'string'},
  {label: 'start_date', type: 'date'},
  {label: 'end_date', type: 'date'},
  {label: 'start_time', type: 'time'},
  {label: 'end_time', type: 'time'},
  {label: 'location', type: 'string'},
  {label: 'tournament_type', type: 'string'},
  {label: 'participants_type', type: 'string'},
  {label: 'no_of_players', type: 'number'},
  {label: 'levels_of_players', type: 'string'},
  {label: 'submission_deadline', type: 'date'},
  {label: 'has_prize', type: 'number'},
  {label: 'prize_value', type: 'number'},
  {label: 'description', type: 'string'},
  {label: 'logo_img', type: 'string'},
];
