-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2lOk/p4q4UIzSrxg
eOUIL7DqZaaJMLj4vWFJKBNkvDKgCgYIKoZIzj0DAQehRANCAATdJzsQPiFhSNVy
f+1prcwefyaVHS/RPJRYZXQdKzAADr4pUV5AzZ87WPnpBG0y5vtQUv4R633/3+mg
VbfuJ8hV
-----END PRIVATE KEY-----