# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "instabadel_mobileapp.xcodeproj")
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "prod.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "instabadel_mobileapp.xcodeproj",
      target_filter: "Instapadel", # Name of your project
      profile: "./builds/prod.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    build_app(workspace: "instabadel_mobileapp.xcworkspace", scheme: "instabadel_mobileapp", clean: true,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
          CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) + " AppStore" # Value of this parameter is the name of the Provisioning Profile. By default, it will be "{bundleId} AppStore"
      }
    },
    build_path: "./builds",
    output_directory: "./builds")
    upload_to_testflight
  end
  lane :version do |options|
    updateVersion(options)
    increment_build_number(xcodeproj: "instabadel_mobileapp.xcodeproj")
  end
  lane :github do |_options|
    create_keychain(
      name: 'login',
      password: 'm.gomaa12',
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
    import_certificate(
      certificate_path: 'distribution.p12',
      certificate_password: 'm.gomaa12',
      keychain_name: 'login',
      keychain_password: 'm.gomaa12'
    )
    install_provisioning_profile(path: 'distribution.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'instabadel_mobileapp.xcodeproj',
      target_filter: 'Instapadel',
      profile: 'distribution.mobileprovision',
      build_configuration: 'Release'
    )
    api_key = app_store_connect_api_key(
      key_id: 'R259M25G3B',
      issuer_id: '69a6de96-5758-47e3-e053-5b8c7c11a4d1',
      key_filepath: 'distribution.p8'
    )
    increment_build_number(xcodeproj: "instabadel_mobileapp.xcodeproj")

    # build_app(workspace: '[Your Project Name].xcworkspace', scheme: '[Your Project Name]')
     build_app(workspace: "instabadel_mobileapp.xcworkspace", scheme: "instabadel_mobileapp")
      upload_to_testflight(      
        api_key: api_key
      )
    # upload_to_app_store(
    #   force: true,
    #   reject_if_possible: true,
    #   skip_metadata: false,
    #   skip_screenshots: true,
    #   languages: ['en'],
    #   release_notes: {
    #     'default' => 'bug fixed',
    #     'en' => 'bug fixed'
    #   },
    #   submit_for_review: true,
    #   precheck_include_in_app_purchases: false,
    #   automatic_release: true,
    #   submission_information: {
    #     add_id_info_uses_idfa: true,
    #     add_id_info_serves_ads: true,
    #     add_id_info_tracks_install: true,
    #     add_id_info_tracks_action: false,
    #     add_id_info_limits_tracking: true,
    #     export_compliance_encryption_updated: false
    #   },
    #   api_key: api_key
    # )
  end
end
