name: Publish iOS to App Store
on:
  push:
    branches:
      - master
jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.9.0"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Install pods
        run: cd ios && pod install && cd ..
      # - name: Install Ios bundle
      #   run: yarn build:ios
      - name: Execute Fastlane command
        run: cd ios && fastlane github
